# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Building project'
  inputs:
    command: 'build'
    projects: |
      DbUpdater/DbUpdater.csproj
      Dbup.Web/Dbup.Web.csproj

- task: DotNetCoreCLI@2
  displayName: 'Prepare publish artifacts'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      DbUpdater/DbUpdater.csproj
      Dbup.Web/Dbup.Web.csproj
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
    ArtifactName: 'drop'
    publishLocation: 'Container'